# Auto DevOps Assistant - One-Click Online Demo
image: gitpod/workspace-python

ports:
  - port: 5000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Install Dependencies
    init: cd backend && pip install -r requirements.txt
    command: cd backend && python app.py

vscode:
  extensions:
    - ms-python.python
