#!/bin/bash
# Quick deployment script for Auto DevOps Assistant

echo "🚀 Auto DevOps Assistant - Quick Cloud Deployment"
echo "=================================================="
echo ""

echo "📋 Step 1: Go to Railway.app and sign up with GitHub"
echo "🔗 https://railway.app"
echo ""
echo "📋 Step 2: Create new project from GitHub repo"
echo "📁 Repository: SHADRACK152/auto-devops-assistant"
echo ""
echo "📋 Step 3: Set environment variables in Railway:"
echo "   GROQ_API_KEY=your-groq-api-key-here"
echo "   FLASK_ENV=production" 
echo "   PORT=5000"
echo ""
echo "📋 Step 4: Get free Groq API key:"
echo "🔗 https://console.groq.com"
echo ""
echo "📋 Step 5: Copy your Railway URL and update docs/app.html"
echo "   Find: const API_BASE_URL = ..."
echo "   Replace with your Railway URL"
echo ""
echo "🎯 Result: Live demo ready for TiDB AgentX Hackathon!"
echo ""
echo "🏆 Your live demo will be at:"
echo "   GitHub Pages: https://shadrack152.github.io/auto-devops-assistant/"
echo "   Live App: https://shadrack152.github.io/auto-devops-assistant/app.html"
echo ""
echo "✅ Perfect for hackathon judges to test your AI-powered solution!"
