# Railway deployment configuration for Auto DevOps Assistant
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
GROQ_API_KEY = { default = "your-groq-api-key-here" }

[networking]
externalPort = 5000
internalPort = 5000
