# Railway deployment configuration for Auto DevOps Assistant
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
# GROQ_API_KEY should be set in Railway dashboard environment variables

[networking]
externalPort = 5000
internalPort = 5000
